In [120]:
''' Q1. What is a Python library? Why do we use Python libraries? 
ans: Python libraries are pre-written collections of code that provide specific functionalities.
We use them to save time, increase productivity, optimize performance, tap into community support,
and leverage specialized features for various tasks. '''

' Q1. What is a Python library? Why do we use Python libraries? \nans: Python libraries are pre-written collections of code that provide specific functionalities.\nWe use them to save time, increase productivity, optimize performance, tap into community support,\nand leverage specialized features for various tasks. '

In [121]:
''' Q2. What is the difference between Numpy array and List?
ans: NumPy arrays are specialized data structures optimized for numerical operations and homogeneous
data types, while lists in Python are general-purpose, dynamic structures allowing heterogeneous elements
and are more versatile for general programming tasks.'''

' Q2. What is the difference between Numpy array and List?\nans: NumPy arrays are specialized data structures optimized for numerical operations and homogeneous\ndata types, while lists in Python are general-purpose, dynamic structures allowing heterogeneous elements\nand are more versatile for general programming tasks.'

In [122]:
import numpy as np

In [123]:
''' Q3.Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

' Q3.Find the shape, size and dimension of the following array?\n[[1, 2, 3, 4]\n[5, 6, 7, 8],\n[9, 10, 11, 12]]'

In [124]:
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [125]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
arr.shape

(3, 4)

In [127]:
arr.size

12

In [128]:
arr.ndim

2

In [129]:
''' Q4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

' Q4. Write python co^e to access the first row of the following array?\n[[1, 2, 3, 4]\n[5, 6, 7, 8],\n[9, 10, 11, 12]]'

In [130]:
arr1 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [131]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [132]:
arr1[0]

array([1, 2, 3, 4])

In [133]:
''' Q5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

' Q5. How do you access the element at the third row and fourth column from the given numpy array?\n[[1, 2, 3, 4],\n[5, 6, 7, 8],\n[9, 10, 11, 12]]'

In [180]:
# To access the third row and fourth column in the given array we can use array slicing in python as below
arr2 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
arr2[2][3]

12

In [135]:
'''Q6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

'Q6. Write code to extract all odd-indexed elements from the given numpy array?\n[[1, 2, 3, 4],\n[5, 6, 7, 8],\n[9, 10, 11, 12]]'

In [136]:
arr3 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [137]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
arr3[arr3 % 2==0]

array([ 2,  4,  6,  8, 10, 12])

In [139]:
'''Q7. How can you generate a random 3x3 matrix with values between 0 and 1?
to generate a matrix of 3x3 we can use numpy module random.rand function which creates a matrix of valued ranges from 0 to 1.
It takes the dimensions of the array as arguments.'''

'Q7. How can you generate a random 3x3 matrix with values between 0 and 1?\nto generate a matrix of 3x3 we can use numpy module random.rand function which creates a matrix of valued ranges from 0 to 1.\nIt takes the dimensions of the array as arguments.'

In [140]:
np.random.rand(3,3)

array([[0.52422886, 0.19764597, 0.0746109 ],
       [0.97509715, 0.22014194, 0.20562079],
       [0.19433027, 0.93746355, 0.0925626 ]])

In [141]:
'''Q8.Describe the difference between np.random.rand and np.random.randn?
The main difference between 'np.random.rand' and 'np.random.randn' in NumPy is:
np.random.rand: This function generates an array of specified shape filled with 
random samples from a uniform distribution over [0, 1). It takes the dimensions of the array as arguments.
np.random.randn: This function generates an array of specified shape filled with random samples
from a standard normal distribution (mean=0, variance=1). It takes the dimensions of the array as arguments.'''

"Q8.Describe the difference between np.random.rand and np.random.randn?\nThe main difference between 'np.random.rand' and 'np.random.randn' in NumPy is:\nnp.random.rand: This function generates an array of specified shape filled with \nrandom samples from a uniform distribution over [0, 1). It takes the dimensions of the array as arguments.\nnp.random.randn: This function generates an array of specified shape filled with random samples\nfrom a standard normal distribution (mean=0, variance=1). It takes the dimensions of the array as arguments."

In [142]:
'''Q9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

'Q9. Write code to increase the dimension of the following array?\n[[1, 2, 3, 4],\n[5, 6, 7, 8],\n[9, 10, 11, 12]]'

In [143]:
arr4 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [144]:
arr4.ndim

2

In [145]:
arr4_3d = np.expand_dims(arr4, axis=0)

In [146]:
arr4_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [147]:
arr4_3d.ndim

3

In [148]:
''' Q10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

' Q10. How to transpose the following array in NumPy?\n[[1, 2, 3, 4]\n[5, 6, 7, 8],\n[9, 10, 11, 12]]'

In [149]:
a = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [150]:
at = a.T

In [151]:
# transposed array:
at

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [152]:
'''11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python
1. Index wise multiplication
2.matrix multiplication
3.add both matrics
4.subtract matrix b from a 
5.divide matrix b by a
'''

'11. Consider the following matrix:\nMatrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]\nMatrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]\nPerform the following operation using Python\n1. Index wise multiplication\n2.matrix multiplication\n3.add both matrics\n4.subtract matrix b from a \n5.divide matrix b by a\n'

In [153]:
matrix_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [154]:
matrix_b = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

In [155]:
matrix_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [156]:
matrix_b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [157]:
#1.Index wise multiplication
matrix_a * matrix_b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [158]:
# 2.matrix multiplication
''' as in this m*n and p*q where n!=p then matrix multiplication is not possible directly
so to achieve in this we have to take transpose of matrix_b and then do the matrix multiplication with matrix_a'''
matrix_a @ matrix_b.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [159]:
#3. add both matrics 
matrix_a + matrix_b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [160]:
# 4.subtract matrix b from a
matrix_a - matrix_b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [161]:
#5.divide matrix b by a
matrix_b / matrix_a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [162]:
'''Q12. Which function in Numpy can be used to swap the byte order of an array?
The function in NumPy that can be used to swap the byte order of an array is np.ndarray.byteswap() example below:.'''

'Q12. Which function in Numpy can be used to swap the byte order of an array?\nThe function in NumPy that can be used to swap the byte order of an array is np.ndarray.byteswap() example below:.'

In [163]:
arr5 = np.array([1, 2, 3, 4])

In [164]:
arr5

array([1, 2, 3, 4])

In [165]:
# arr_swapped = arr5.byteswap()

In [166]:
arr_swapped

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744])

In [167]:
'''13. What is the significance of the np.linalg.inv function?
The np.linalg.inv() function in NumPy calculates the inverse of a square matrix. example below: '''

'13. What is the significance of the np.linalg.inv function?\nThe np.linalg.inv() function in NumPy calculates the inverse of a square matrix. example below: '

In [168]:
arr6 = np.array([[1, 2],[3, 4]])

In [169]:
arr6

array([[1, 2],
       [3, 4]])

In [170]:
inverse = np.linalg.inv(arr6)

In [171]:
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [172]:
'''Q 14. What does the np.reshape function do, and how is it used?
The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data.
It allows you to rearrange the elements of an array into a new shape, provided that the total number of elements
remains the same. example below:'''

'Q 14. What does the np.reshape function do, and how is it used?\nThe np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data.\nIt allows you to rearrange the elements of an array into a new shape, provided that the total number of elements\nremains the same. example below:'

In [173]:
arr7 = np.random.randint(1,5,size=(3,4))

In [174]:
# original array
arr7

array([[3, 3, 3, 1],
       [3, 3, 2, 4],
       [2, 2, 3, 1]])

In [175]:
#reshaped array
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [176]:
'''Q15. What is broadcasting in Numpy?
Broadcasting in NumPy allows arrays of different shapes to be combined in arithmetic operations by automatically
adjusting their shapes to make them compatible, typically by replicating smaller arrays along missing dimensions.
This enables concise and efficient computation of operations even when arrays have different shapes.
example below'''


'Q15. What is broadcasting in Numpy?\nBroadcasting in NumPy allows arrays of different shapes to be combined in arithmetic operations by automatically\nadjusting their shapes to make them compatible, typically by replicating smaller arrays along missing dimensions.\nThis enables concise and efficient computation of operations even when arrays have different shapes.\nexample below'

In [177]:
arr8 = np.array([[1, 2, 3],[4,5,6]])

In [178]:
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
arr8 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])